[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["zekesonxx <zeke@zekesonxx.com>"]

[dependencies]
lazy_static = "1.2.0"

[profile.dev]
opt-level = 2

[profile.release]
lto = true
opt-level = 3
